sudo: false
language: python
python: "3.6"

before_install:
  - sudo apt-get install pandoc pandoc-citeproc
  - bash scripts/before_script.sh

install:
  - python3 setup.py install

script:
  - cd test-files && mdp -vvv
